spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task_manager
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
  #      data-locations: classpath:data.sql
  #      schema-locations: classpath:schema.sql
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    show-sql: true
#  config:
#    activate:
#      on-profile: local