spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task_manager
    username: postgres
    password: postgres
  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    show-sql: true
app:
  jwt:
    secret: "8fQ2mL7xP9vB4nK6sD3hJ5wR1tY8uI0o"
    expiration-seconds: 36000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics #"*" # prometeus - если подключить, то обычные ручки перестают работать. Если подключать то наверное надо к графане дальше отдавать