CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     username VARCHAR(255) NOT NULL UNIQUE,
                                     password VARCHAR(255) NOT NULL,
                                     role VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     description VARCHAR(255) NOT NULL,
                                     task_status VARCHAR(50) NOT NULL,
                                     author_id BIGINT NOT NULL,
                                     executor_id BIGINT,
                                     created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                                     updated_at TIMESTAMP WITH TIME ZONE,
                                     completed_at TIMESTAMP WITH TIME ZONE,
                                     is_deleted BOOLEAN NOT NULL DEFAULT FALSE,

                                     CONSTRAINT fk_tasks_author
                                         FOREIGN KEY (author_id)
                                             REFERENCES users (id),

                                     CONSTRAINT fk_tasks_executor
                                         FOREIGN KEY (executor_id)
                                             REFERENCES users (id)
);

INSERT INTO users (
    username,
    password,
    role
)
VALUES
    (
        'test_1',
        '$2a$10$Fby9/8Q1UJrhOyHFWTTs1Ox7OshGLc4UKGBm/0HkHjR5DJJCsetK.',
        'ADMIN'
    ),
    (
        'test_2',
        '$2a$10$u/zA3hwO2Bc/YZ/o4JC40uCMIaJiM1B25A1ObDqoRTubcEQqBNt3W',
        'USER'
    );

INSERT INTO tasks (
    description,
    task_status,
    author_id,
    executor_id,
    created_at,
    updated_at,
    completed_at,
    is_deleted
)
VALUES
    (
        'Редизайн главной',
        'CREATED',
        1,
        NULL,
        NOW(),
        NULL,
        NULL,
        FALSE
    ),
    (
        'Правки по мп',
        'IN_PROGRESS',
        2,
        1,
        NOW(),
        NULL,
        NULL,
        FALSE
    ),
    (
        'Правки по лк',
        'DONE',
        2,
        2,
        NOW(),
        NULL,
        NOW(),
        FALSE
    );