input {
  file {
    path => "/usr/share/logstash/app-logs/spring-boot-app.log"
    start_position => "beginning"
    sincedb_path => "/usr/share/logstash/data/sincedb-spring-boot-app"
    stat_interval => 1
    codec => multiline {
      pattern => "^%{TIMESTAMP_ISO8601}"
      negate => true
      what => "previous"
    }
  }
}

filter {
  grok {
    match => {
      "message" => "%{TIMESTAMP_ISO8601:log_timestamp} \[%{DATA:thread}\] %{LOGLEVEL:level}\s+%{DATA:logger} - %{GREEDYDATA:log_message}"
    }
  }

  date {
    match => [ "log_timestamp", "yyyy-MM-dd HH:mm:ss.SSS", "ISO8601" ]
    target => "@timestamp"
    remove_field => [ "log_timestamp" ]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "task-manager-logs-%{+YYYY.MM.dd}"
    ilm_enabled => false
  }
}
